replicaCount: 1

image:
  repository: ghcr.io/investment-alert-system/stock-data-streamer/app
  pullPolicy: IfNotPresent
  tag: "0b68369e3b65305a6b3fe94f70070233a7dd58c1"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "400m"
  limits:
    memory: "1024Mi"
    cpu: "800m"

ingress:
  domain: acceleratedit.de
  #domain: localhost
