replicaCount: 1

image:
  repository: ghcr.io/investment-alert-system/stock-data-streamer/app
  pullPolicy: IfNotPresent
  tag: "b1535f3f6e8104b21e1729aa89d7d1a2e0d4a19d"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "400m"
  limits:
    memory: "1024Mi"
    cpu: "800m"

ingress:
  domain: localhost
