replicaCount: 1

image:
  repository: ghcr.io/investment-alert-system/investment-alert-frontend/app
  pullPolicy: IfNotPresent
  tag: "1b66b491da49499f920ad962b17ab868fb77d472"

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    memory: "512Mi"
    cpu: "400m"
  limits:
    memory: "1024Mi"
    cpu: "800m"

ingress:
  domain: acceleratedit.de
