apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "project-launchpad.fullname" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`investment-alert-frontend.{{ .Values.ingress.domain }}`)
      kind: Rule
      services:
        - name: "{{.Release.Name}}-project-launchpad"
          port: {{.Values.service.port}}
