apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alertmanager.acceleratedit.de`)
      kind: Rule
      services:
        - name: {{.Release.Name}}-kube-prometheus-alertmanager
          port: 9093