apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.acceleratedit.de`)
      kind: Rule
      services:
        - name: prometheus-kube-prometheus-prometheus
          port: 9090