apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-data-streamer.fullname" . }}
  labels:
    {{- include "stock-data-streamer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080  # Ändern Sie dies auf 8080
      protocol: TCP
      name: http
  selector:
    {{- include "stock-data-streamer.selectorLabels" . | nindent 4 }}
